name: Generate stats card

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          theme: monokai
          username: maurodesouza
          output_path: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # muda para a branch output (ou cria)
          git fetch origin output || true
          git checkout output || git checkout -b output

          # copia só o arquivo gerado
          mkdir -p trophies
          cp dist/trophy.svg trophies/trophy.svg

          git add trophies/trophy.svg
          git commit -m "update trophy" || echo "no changes"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
